#!/usr/bin/env bash

x11rcd=${XDG_CONFIG_HOME:-~/.config}/X11

shopt -s nullglob
for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  source "$f"
done

xrdb -merge "$x11rcd/Xresources"
xmodmap "$x11rcd/Xmodmap"
xset -b m 0 1 r rate 150 25 -dpms dpms 0 0 0 s off
xrandr --output VGA-1 --rotate left

unclutter &
picom --experimental-backends &

source "$x11rcd/xinit.d/${WM:=i3}" \
  1> "${XDG_CACHE_HOME}/xsession$DISPLAY-stdout" \
  2> "${XDG_CACHE_HOME}/xsession$DISPLAY-stderr"
